---

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when:
    - ansible_os_family == "RedHat"
    - freeipa_server_enable_epel_repo

- name: Add EPEL GPG key
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
  when:
    - ansible_os_family == "RedHat"
    - freeipa_server_enable_epel_repo

- name: Install FreeIPA server packages
  package:
    name: "{{ freeipa_server_pkgs }}"
    state: present
  delay: 10
  register: result
  retries: 3
  until: result is succeeded

